# Use node:alpine for a smaller backend image
FROM node:16-alpine

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json to leverage Docker cache for faster builds
COPY package.json package-lock.json ./

# Install only production dependencies
RUN npm install --production

# Copy the backend code after installing dependencies to avoid invalidating cache
COPY . ./

# Expose port 5000
EXPOSE 5000

# Set the command to start the application
CMD ["node", "index.js"]
